### ISSUE TITLE
26 de Junho a 09 de Julho: "Sub-requisitos" do Kanban

### ISSUE THREAD

**Issue by BeyondMagic** [cerejeiros/bloom#39]
dawd

**Comment by kaioenzo** [comment]
"Na Página de Registro precisa ter um auxílio visual quando a senha não atender os requerimentos."
As mensagens de erro não são suficiente? Acho que vou criar um [Paper Tooltip](https://callstack.github.io/react-native-paper/docs/components/Tooltip/) pra isso!

"Na Págian de Registro há um estado de IsLoading, podemos usar ele para mostrar mostrar uma tela de carregamento depois de apertar para registrar."
Acredito que poderíamos apenas deixar o botão com loading state no botão!
@cerejeiros/front-end

**Comment by BeyondMagic** [comment]
> As mensagens de erro não são suficiente?
 
Sim! Inclusive recomendo usar `window.alert()` em troca de algo que necessite de mais trabalho.

O Paper Tooltip parece ser ótimo para dar mais visibilidade ao input.

> Acredito que poderíamos apenas deixar o botão com loading state no botão!

Sim, bem melhor. Na correria do momento escrevi tela, mas um botão é mais adequado.

**Comment by kaioenzo** [comment]
@Neoprot resolve isso do tooltip ou outra solução que você curtir!

**Comment by BeyondMagic** [comment]
Passados para aqui: https://github.com/orgs/cerejeiros/projects/2/views/1?pane=issue&itemId=33803798
